import { Inter } from "next/font/google";
import "../globals.css";
import CardSingUp from "../components/CardSignUp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ember",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="singup__container">
          <CardSingUp />
          {children}
        </div>
      </body>
    </html>
  );
}